Repository DesertBot/DesertBot, pull requests merged in 2019-05, with the labels that each got.

#145 Replace LRR module with generic RSS module
  desertbot/modules/commands/LRR.py
  desertbot/modules/commands/RSS.py
Labels: help wanted, module

#149 Fix type hints for help() and displayHelp()
  desertbot/moduleinterface.py
  desertbot/modules/commandinterface.py
  desertbot/modules/commands/Lists.py
Labels: bug, core

#153 [Comic] generate as many text colours as there are characters
  desertbot/modules/commands/Comic.py
Labels: enhancement, module

#151 Shorten URLs in messages before posting
  desertbot/modules/commands/Comic.py
Labels: enhancement, module

#155 Port PyHeufyBot's Tell command
  desertbot/modules/commands/Tell.py
  desertbot/utils/string.py
  migration/pyheufybot/tell.py
Labels: module

#165 Port PyHeufyBot's log searching module
  desertbot/modules/commands/LogSearch.py
Labels: module

#171 [RSS] sort the feed before checking the latest date
  desertbot/modules/commands/RSS.py
Labels: enhancement, module
